publishDir = "docs"

baseURL = "https://blog.rickyfun.net"
languageCode = "zh-tw"
defaultContentLanguage = "zh"
title = "LOOPBAI"
theme = "cupper-hugo-theme"
googleAnalytics = ""
disqusShortname = ""
enableGitInfo = false

[taxonomies]
  tag = "tags"

#[permalinks]
#  post = "/:filename/"

[imaging]
  quality = 99

[params]
  # Meta description
  homeMetaContent = "Software Engineer Life"

  # Site description
  description = "Software Engineer Life"
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Mon, 02 Jan 2006 15:04:05 +0800"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
#  [[menu.nav]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
#  [[menu.nav]]
#    name = "RSS"
#    url = "/index.xml"
#    weight = 5
